#!/usr/bin/env python3
"""Assemble data/i18n/<lang>/<part>.js from translation chunks.

Translations are authored as flat {key: translation} JSON under
tools/content-src/<lang>/ (any number of files, any grouping — they are merged).
Keys are the catalog keys from tools/extract-content-catalog.py.

This routes each key to the content file it belongs to and writes one
ContentI18n.register() call per part, so a language pack can be fetched in
pieces and a partial pack still works (untranslated keys fall back to English
at apply() time).

    python tools/build-content-pack.py ja
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PARTS = ["fundamentals", "orchestration", "architecture", "delivery", "glossary", "references"]

NATIVE = {
    "es": "Español", "pt": "Português", "fr": "Français", "de": "Deutsch",
    "it": "Italiano", "zh": "简体中文", "ja": "日本語", "hi": "हिन्दी", "ar": "العربية",
}


def part_for(key):
    """Which pack file a catalog key belongs to."""
    if key.startswith("glossary:"):
        return "glossary"
    if key.startswith("reference:"):
        return "references"
    if key.startswith("domain:"):
        return key.split(":", 2)[1]      # domain:<id>:...
    return None


def main():
    lang = sys.argv[1] if len(sys.argv) > 1 else "ja"
    src_dir = os.path.join(ROOT, "tools", "content-src", lang)
    if not os.path.isdir(src_dir):
        sys.exit(f"no translation sources at tools/content-src/{lang}/")

    with open(os.path.join(ROOT, "tools", "content-catalog.json"), encoding="utf-8") as f:
        catalog = json.load(f)
    valid = {u["key"] for u in catalog["units"]}

    merged, unknown = {}, []
    for name in sorted(os.listdir(src_dir)):
        if not name.endswith(".json"):
            continue
        with open(os.path.join(src_dir, name), encoding="utf-8") as f:
            chunk = json.load(f)
        for k, v in chunk.items():
            if k not in valid:
                unknown.append((name, k))
                continue
            if v and str(v).strip():
                merged[k] = v

    if unknown:
        print(f"WARNING: {len(unknown)} key(s) not in the catalog (stale? typo?):")
        for name, k in unknown[:8]:
            print(f"  {name}: {k}")

    out_dir = os.path.join(ROOT, "data", "i18n", lang)
    os.makedirs(out_dir, exist_ok=True)

    total = 0
    for part in PARTS:
        sub = {k: v for k, v in merged.items() if part_for(k) == part}
        expected = sum(1 for k in valid if part_for(k) == part)
        path = os.path.join(out_dir, part + ".js")
        header = (f"/* KCNA Prep study content — {NATIVE.get(lang, lang)} ({lang}) / {part}. "
                  f"Generated by tools/build-content-pack.py. */\n")
        body = json.dumps(sub, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(header)
            f.write(f'ContentI18n.register("{lang}", "{part}", {body});\n')
        total += len(sub)
        pct = (100.0 * len(sub) / expected) if expected else 100.0
        print(f"  {part:<14} {len(sub):>5} / {expected:<5} ({pct:5.1f}%)  "
              f"{os.path.getsize(path) // 1024} KB")

    print(f"{total} / {len(valid)} units -> data/i18n/{lang}/  "
          f"({100.0 * total / len(valid):.1f}% coverage)")


if __name__ == "__main__":
    main()
